.TH "PXL PREVIEW" "1" "23-Mar-2019" "None" "pxl preview Manual"
.SH NAME
pxl\-preview \- Run a local webserver on build output
.SH SYNOPSIS
.B pxl preview
[OPTIONS]
.SH DESCRIPTION
Run a local webserver on build output
.SH OPTIONS
.TP
\fB\-\-port\fP INTEGER
Port to use
.TP
\fB\-\-bind\fP TEXT
Address to bind on (default: all interfaces)
