.TH "PXL" "1" "23-Mar-2019" "None" "pxl Manual"
.SH NAME
pxl \- Photo management script for S3 albums.
.SH SYNOPSIS
.B pxl
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Photo management script for S3 albums.
.SH COMMANDS
.PP
\fBinit\fP
  Initialize pxl configuration
  See \fBpxl-init(1)\fP for full documentation on the \fBinit\fP command.
.PP
\fBclean\fP
  Clean pxl files from system
  See \fBpxl-clean(1)\fP for full documentation on the \fBclean\fP command.
.PP
\fBupload\fP
  Upload a directory to the photo hosting.
  See \fBpxl-upload(1)\fP for full documentation on the \fBupload\fP command.
.PP
\fBbuild\fP
  Build a static site based on current state.
  See \fBpxl-build(1)\fP for full documentation on the \fBbuild\fP command.
.PP
\fBpreview\fP
  Run a local webserver on build output
  See \fBpxl-preview(1)\fP for full documentation on the \fBpreview\fP command.
.PP
\fBdeploy\fP
  Deploy the static output.
  See \fBpxl-deploy(1)\fP for full documentation on the \fBdeploy\fP command.
